server.port=8082

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/student_management_System}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:123456}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=false

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jpa.hibernate.ddl-auto=update

# App-specific configs
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
app.jwt.secret=${JWT_SECRET:407A46725678309A4D3B592D3F4428472B4B6250655368566D59713374367739}
app.jwt.expiration-ms=86400000

app.admin.initial-username=admin
app.admin.initial-password=adminpassword
app.admin.initial-email=admin@trainingcenter.com




