server.port=8082

# ==========================================
# MySQL Database Configuration
# ==========================================
spring.datasource.url=jdbc:mysql://localhost:3306/student_management_System?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=false

spring.jackson.serialization.write-dates-as-timestamps=false

# App-specific configs
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
app.jwt.secret=407A46725678309A4D3B592D3F4428472B4B6250655368566D59713374367739
app.jwt.expiration-ms=86400000

# Initial Admin Seeding
app.admin.initial-username=admin
app.admin.initial-password=adminpassword
app.admin.initial-email=admin@trainingcenter.com
